Repository JohnSnowLabs/langtest, pull requests merged in 2023-09, with the labels that each got.

#732 Ensure uniqueness of sentence duplication
  langtest/augmentation/__init__.py
  langtest/transform/__init__.py
  langtest/transform/utils.py
  tests/test_augmentation.py
  tests/test_harness.py
Labels: current release

#740 fix :langchain for text classification task
  langtest/modelhandler/transformers_modelhandler.py
Labels: bug

#757 Fix/bias bug in calling Harness.data
  langtest/datahandler/datasource.py
  langtest/langtest.py
  manual_tests/test_llms.py
Labels: bug, fixes

#760 feature/Sensitivity-Test
  demo/tutorials/llm_notebooks/Sensitivity_Test.ipynb
  langtest/data/config/sensitivity_config.yml
  langtest/datahandler/datasource.py
  langtest/langtest.py
  langtest/modelhandler/llm_modelhandler.py
  langtest/modelhandler/modelhandler.py
  langtest/modelhandler/transformers_modelhandler.py
  langtest/transform/__init__.py
  langtest/transform/sensitivity.py
  langtest/utils/custom_types/__init__.py
  langtest/utils/custom_types/sample.py
  langtest/utils/hf_model_n_tokenizer.py
  tests/test_sensitivity.py
Labels: feature, current release

#769 hot-fix: non Bias dataset loading now
  langtest/langtest.py
Labels: fixes

#788 Fix/wino bias
  langtest/modelhandler/transformers_modelhandler.py
  langtest/utils/custom_types/sample.py
Labels: fixes, current release

#806 Fixes/fixvalidate conlls
  langtest/datahandler/datasource.py
Labels: fixes
