Repository JohnSnowLabs/langtest, pull requests merged in 2023-07, with the labels that each got.

#574 fix pipeline model loading
  demo/tutorials/misc/Augmentation_Control_Notebook.ipynb
  langtest/langtest.py
Labels: bug, v1.6.0

#588 feature: add poetry
  .github/workflows/build_and_test.yml
  .github/workflows/requirements.txt
  poetry.lock
  pyproject.toml
Labels: maintenance

#597 feature: installation modes
  .github/workflows/build_and_test.yml
  .pre-commit-config.yaml
  langtest/modelhandler/modelhandler.py
  langtest/transform/__init__.py
  langtest/transform/accuracy.py
  langtest/transform/fairness.py
  langtest/transform/representation.py
  langtest/transform/toxicity.py
  langtest/utils/custom_types/sample.py
  poetry.lock
  pyproject.toml
Labels: maintenance

#592 feature/Listing available tests
  langtest/langtest.py
Labels: feature, current release

#593 Save augmentations
  langtest/augmentation/__init__.py
  langtest/langtest.py
  tests/test_augmentation.py
Labels: feature, current release

#613 fix(dependency): missing huggingface-hub dependency
  poetry.lock
  pyproject.toml
Labels: bug

#609 Dataset/BBQ data
  langtest/data/BBQ/BBQ-test-tiny.jsonl
  langtest/data/BBQ/BBQ-test.jsonl
  langtest/datahandler/datasource.py
  langtest/utils/custom_types/helpers.py
  langtest/utils/custom_types/sample.py
Labels: current release

#623 Fix/hf datasets summarization default prompt
  .github/workflows/build_and_test.yml
  langtest/utils/custom_types/helpers.py
  langtest/utils/custom_types/sample.py
Labels: bug

#619 chore/nbs-website-update
  demo/tutorials/llm_notebooks/AI21_QA_Summarization_Testing_Notebook.ipynb
  demo/tutorials/llm_notebooks/Azure_OpenAI_QA_Summarization_Testing_Notebook.ipynb
  demo/tutorials/llm_notebooks/Cohere_QA_Summarization_Testing_Notebook.ipynb
  demo/tutorials/llm_notebooks/HuggingFaceHub_QA_Summarization_Testing_Notebook.ipynb
  demo/tutorials/llm_notebooks/OpenAI_QA_Summarization_Testing_Notebook.ipynb
  demo/tutorials/llm_notebooks/dataset-notebooks/BBQ_dataset.ipynb
  demo/tutorials/llm_notebooks/dataset-notebooks/HellaSwag_Question_Answering.ipynb
  demo/tutorials/llm_notebooks/dataset-notebooks/NarrativeQA_Question_Answering.ipynb
  demo/tutorials/llm_notebooks/dataset-notebooks/OpenbookQA_dataset.ipynb
  demo/tutorials/llm_notebooks/dataset-notebooks/TruthfulQA_dataset.ipynb
  demo/tutorials/llm_notebooks/dataset-notebooks/mmlu_dataset.ipynb
  demo/tutorials/llm_notebooks/dataset-notebooks/quac_dataset.ipynb
  demo/tutorials/misc/HuggingFace_Dataset_Notebook.ipynb
  demo/tutorials/misc/RuntimeTest_Notebook.ipynb
  demo/tutorials/test-specific-notebooks/Robustness_DEMO.ipynb
  docs/pages/docs/data.md
  docs/pages/docs/generate.md
  docs/pages/tests/robustness/adjective_antonym_swap.md
  docs/pages/tests/robustness/adjective_synonym_swap.md
  docs/pages/tests/test.md
  docs/pages/tutorials/tutorials.md
Labels: documentation

#631 Hot-Fixes
  langtest/langtest.py
  langtest/transform/robustness.py
Labels: fixes

#640 fix(dependency): monkey patch import in toxicity
  langtest/transform/toxicity.py
Labels: bug

#605 Refactor/change runtime speed into a test
  demo/tutorials/misc/PerformanceTest_Notebook.ipynb
  demo/tutorials/misc/RuntimeTest_Notebook.ipynb
  demo/tutorials/misc/Templatic_Augmentation_Notebook.ipynb
  langtest/augmentation/__init__.py
  langtest/data/config/translation_transformers_config.yml
  langtest/langtest.py
  langtest/transform/__init__.py
  langtest/transform/performance.py
  langtest/utils/custom_types/sample.py
  tests/fixtures/config_performance.yaml
  tests/test_performance.py
  tests/test_translation.py
Labels: current release

#682 Pytest for fairness class
  langtest/transform/__init__.py
  langtest/transform/fairness.py
  tests/test_fairness.py
Labels: current release

#681 fix/sentences containing white spaces for ConllDataset
  langtest/datahandler/datasource.py
Labels: bug
