Repository JohnSnowLabs/langtest, pull requests merged in 2023-08, with the labels that each got.

#683 Feature/ml flow integration
  langtest/langtest.py
  poetry.lock
  pyproject.toml
  tests/test_mlflow.py
Labels: feature, current release

#653 Feature/hf dataset augmentation
  demo/tutorials/misc/Augmentation_Control_Notebook.ipynb
  demo/tutorials/misc/Templatic_Augmentation_Notebook.ipynb
  docs/pages/docs/generate_augmentation.md
  langtest/augmentation/__init__.py
  langtest/langtest.py
  langtest/pipelines/transformers/ner_pipeline.py
  tests/test_augmentation.py
Labels: feature, current release

#700 Improve unit test coverage
  langtest/transform/__init__.py
  langtest/transform/accuracy.py
  tests/test_accuracy.py
  tests/test_robustness.py
Labels: current release

#701 Docs/Added Contribution Guidelines
  CONTRIBUTING.md
  docs/_data/navigation.yml
  docs/pages/docs/contribute.md
Labels: documentation, current release

#705 pytest/Representation Classes
  langtest/datahandler/datasource.py
  langtest/transform/representation.py
  langtest/utils/custom_types/sample.py
  tests/test_representation.py
Labels: current release

#708 Feature/explore prompt injection tests
  langtest/data/config/security_config.yml
  langtest/data/security/Prompt-Injection-Attack.jsonl
  langtest/datahandler/datasource.py
  langtest/langtest.py
  langtest/modelhandler/llm_modelhandler.py
  langtest/modelhandler/modelhandler.py
  langtest/transform/__init__.py
  langtest/transform/security.py
  langtest/utils/custom_types/__init__.py
  langtest/utils/custom_types/helpers.py
  langtest/utils/custom_types/sample.py
  setup.py
Labels: current release

#706 Refacto/Updated format of Harness
  langtest/augmentation/__init__.py
  langtest/datahandler/datasource.py
  langtest/langtest.py
  langtest/pipelines/transformers/ner_pipeline.py
  tests/test_augmentation.py
  tests/test_harness.py
  tests/test_mlflow.py
  tests/test_performance.py
  tests/test_spacy_model.py
  tests/test_sparknlp_model.py
  tests/test_translation.py
Labels: current release

#713 Upload model/dataset to hf
  demo/tutorials/misc/Upload_to_HuggingFace_Hub.ipynb
  langtest/langtest.py
Labels: feature, current release

#724 Datasets/lm evaluation library
  demo/tutorials/llm_notebooks/dataset-notebooks/ASDiv_dataset.ipynb
  demo/tutorials/llm_notebooks/dataset-notebooks/Bigbench_dataset.ipynb
  demo/tutorials/llm_notebooks/dataset-notebooks/LogiQA_dataset.ipynb
  langtest/data/Bigbench/AbstractNarrativeUnderstanding/Abstract-narrative-understanding-test-tiny.jsonl
  langtest/data/Bigbench/AbstractNarrativeUnderstanding/Abstract-narrative-understanding-test.jsonl
  langtest/data/Bigbench/CausalJudgment/causal-judgment-test-tiny.jsonl
  langtest/data/Bigbench/CausalJudgment/causal-judgment-test.jsonl
  langtest/data/Bigbench/DisambiguationQA/DisambiguationQA-test-tiny.jsonl
  langtest/data/Bigbench/DisambiguationQA/DisambiguationQA-test.jsonl
  langtest/data/Bigbench/DisflQA/disfl-qa-test-tiny.jsonl
  langtest/data/Bigbench/DisflQA/disfl-qa-test.jsonl
  langtest/data/LogiQA/LogiQA-test-tiny.jsonl
  langtest/data/LogiQA/LogiQA-test.jsonl
  langtest/data/asdiv/asdiv-test-tiny.jsonl
  langtest/data/asdiv/asdiv-test.jsonl
  langtest/datahandler/datasource.py
  langtest/utils/custom_types/helpers.py
  setup.py
Labels: current release

#725 Restructure BBQ data
  demo/tutorials/llm_notebooks/dataset-notebooks/BBQ_dataset.ipynb
  langtest/data/BBQ/BBQ-test-tiny.jsonl
  langtest/data/BBQ/BBQ-test.jsonl
  langtest/utils/custom_types/helpers.py
Labels: fixes, current release

#734 Bug/augmentation output differs from input file
  langtest/augmentation/__init__.py
  langtest/datahandler/datasource.py
  langtest/datahandler/format.py
  langtest/transform/robustness.py
  tests/test_datasource.py
Labels: bug, fixes

#737 Feature/disinformation test
  demo/tutorials/llm_notebooks/Disinformation_Test.ipynb
  langtest/data/NarrativeWedging/Narrative_Wedging.jsonl
  langtest/data/config/disinformation_huggingface_config.yml
  langtest/data/config/disinformation_openai_config.yml
  langtest/datahandler/datasource.py
  langtest/langtest.py
  langtest/modelhandler/llm_modelhandler.py
  langtest/modelhandler/modelhandler.py
  langtest/transform/__init__.py
  langtest/utils/custom_types/__init__.py
  langtest/utils/custom_types/helpers.py
  langtest/utils/custom_types/sample.py
Labels: current release
