Repository JohnSnowLabs/langtest, pull requests merged in 2023-06, with the labels that each got.

#483 Hotfix/fixed some tests and refactored number_to_word.py
  nlptest/transform/robustness.py
  nlptest/utils/number_to_word.py
  tests/test_robustness.py
Labels: fixes

#488 Feature/create toxicity test 438
  nlptest/data/toxicity/toxicity-test-tiny.jsonl
  nlptest/datahandler/datasource.py
  nlptest/modelhandler/llm_modelhandler.py
  nlptest/modelhandler/modelhandler.py
  nlptest/nlptest.py
  nlptest/transform/__init__.py
  nlptest/transform/toxicity.py
  nlptest/utils/custom_types/sample.py
  setup.py
Labels: feature

#507 Fix/context-issue
  nlptest/transform/robustness.py
Labels: bug, fixes

#506 supports custom proportions for augument
  nlptest/augmentation/__init__.py
  nlptest/nlptest.py
  tests/test_augmentation.py
Labels: feature

#511 feature/Add support for hf datasets for text classification task
  nlptest/datahandler/datasource.py
  nlptest/nlptest.py
  tests/test_harness.py
Labels: feature, v1.5.0

#514 Features/model comparisons
  nlptest/nlptest.py
Labels: feature

#515 Feature/add runtime tests
  nlptest/augmentation/__init__.py
  nlptest/nlptest.py
  nlptest/transform/__init__.py
  nlptest/utils/custom_types/sample.py
Labels: feature

#519 Chore/website updates
  docs/pages/docs/data.md
  docs/pages/docs/harness.md
  docs/pages/docs/one_liner.md
  docs/pages/tutorials/tutorials.md
  setup.py
Labels: documentation

#549 Hot-fix/Restructure load HF dataset conditions
  nlptest/nlptest.py
Labels: fixes, v1.6.0

#555 feature/controlling the proportion of the words in the sentence that get transformed
  nlptest/transform/__init__.py
  nlptest/transform/robustness.py
  nlptest/utils/custom_types/sample.py
  tests/test_robustness.py
Labels: feature, v1.6.0

#548 Combine multiple perturbations as 1 test
  nlptest/nlptest.py
  nlptest/transform/__init__.py
  nlptest/transform/robustness.py
  nlptest/utils/custom_types/sample.py
  tests/test_robustness.py
Labels: feature, v1.6.0

#564 feature/Custom proportion for multiple perturbations
  nlptest/transform/__init__.py
  nlptest/transform/robustness.py
  nlptest/utils/custom_types/sample.py
Labels: feature, v1.6.0

#545 Feature/add translation support
  nlptest/data/Translation/translation-test-tiny.jsonl
  nlptest/data/config/translation_johnsnowlabs_config.yml
  nlptest/data/config/translation_transformers_config.yml
  nlptest/datahandler/datasource.py
  nlptest/modelhandler/jsl_modelhandler.py
  nlptest/modelhandler/modelhandler.py
  nlptest/modelhandler/spacy_modelhandler.py
  nlptest/modelhandler/transformers_modelhandler.py
  nlptest/nlptest.py
  nlptest/transform/robustness.py
  nlptest/utils/SentenceTransformer.py
  nlptest/utils/custom_types/__init__.py
  nlptest/utils/custom_types/helpers.py
  nlptest/utils/custom_types/output.py
  nlptest/utils/custom_types/sample.py
  nlptest/utils/util_metrics.py
  setup.py
  tests/test_translation.py
Labels: feature, v1.6.0
