Repository JohnSnowLabs/langtest, pull requests merged in 2023-10, with the labels that each got.

#790 Hugging Face QA Support and Fix QA/Summarization Dataset Issues for Accuracy/Fairness Testing
  demo/tutorials/misc/HuggingFace_Dataset_Notebook.ipynb
  langtest/datahandler/datasource.py
  langtest/langtest.py
  langtest/transform/__init__.py
Labels: current release

#808 Feature/crows pairs
  langtest/data/CrowS-Pairs/crows_pairs_anonymized_masked.csv
  langtest/data/config/crows_pairs_config.yml
  langtest/datahandler/datasource.py
  langtest/langtest.py
  langtest/modelhandler/modelhandler.py
  langtest/modelhandler/transformers_modelhandler.py
  langtest/transform/__init__.py
  langtest/utils/custom_types/__init__.py
  langtest/utils/custom_types/sample.py
  setup.py
  tests/test_crowspairs.py
Labels: feature, current release

#821 Test LLMs on wino-Bias
  demo/tutorials/llm_notebooks/Wino_Bias_LLM.ipynb
  langtest/data/Wino-Bias/wino-bias-test.jsonl
  langtest/data/config/wino_ai21_config.yml
  langtest/data/config/wino_huggingface_config.yml
  langtest/data/config/wino_openai_config.yml
  langtest/datahandler/datasource.py
  langtest/langtest.py
  langtest/modelhandler/modelhandler.py
  langtest/modelhandler/transformers_modelhandler.py
  langtest/utils/custom_types/helpers.py
  langtest/utils/custom_types/sample.py
Labels: feature, current release

#820 Feature/custom model api endpoint support
  langtest/langtest.py
  langtest/modelhandler/custom_modelhandler.py
  langtest/modelhandler/modelhandler.py
Labels: feature

#835 update data path
  setup.py
Labels: fixes

#860 Refactor/report section
  README.md
  docs/pages/tests/test.md
  langtest/augmentation/__init__.py
  langtest/langtest.py
  langtest/utils/report_utils.py
Labels: 🔧 Refacto
