Repository JohnSnowLabs/langtest, pull requests merged in 2023-11, with the labels that each got.

#861 updated Evaluation_Metrics notebook
  demo/tutorials/misc/Evaluation_Metrics.ipynb
Labels: 📚 Documentation

#862 Update issue templates
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/⭐---feature-request.md
  .github/ISSUE_TEMPLATE/🐞---bug-report.md
  .github/ISSUE_TEMPLATE/💡--improvements.md
Labels: 📚 Documentation, 💡Enhancements

#863 Created CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
  README.md
Labels: 📚 Documentation, 💡Enhancements

#866 Refactor/add configurable parameters
  demo/tutorials/task-specific-notebooks/Crows_Pairs_Notebook.ipynb
  demo/tutorials/task-specific-notebooks/StereoSet_Notebook.ipynb
  demo/tutorials/task-specific-notebooks/Wino_Bias.ipynb
  docs/pages/tests/clinical/demographic-bias.md
  docs/pages/tests/crows-pairs/common_stereotypes.md
  docs/pages/tests/stereoset/intersentence.md
  docs/pages/tests/stereoset/intrasentence.md
  docs/pages/tests/wino-bias/gender-occupational-stereotype-llm.md
  docs/pages/tests/wino-bias/gender-occupational-stereotype.md
  langtest/data/config/crows_pairs_config.yml
  langtest/data/config/stereoset_config.yml
  langtest/data/config/wino_config.yml
  langtest/data/config/wino_huggingface_config.yml
  langtest/embeddings/openai.py
  langtest/langtest.py
  langtest/modelhandler/transformers_modelhandler.py
  langtest/transform/__init__.py
  langtest/utils/custom_types/sample.py
Labels: 💡Enhancements, 🚀 Current Release

#871 Added citation for the repo
  CITATION.cff
Labels: 📚 Documentation, 💡Enhancements

#873 Investigate TestFactory.task for Task Transition Errors
  langtest/transform/__init__.py
Labels: 🐛 Bug

#859 updated wino evaluation
  langtest/utils/custom_types/sample.py
Labels: 💡Enhancements, 🚀 Current Release

#875 Website Updates
  README.md
  demo/tutorials/llm_notebooks/Disinformation_Test.ipynb
  demo/tutorials/llm_notebooks/Wino_Bias_LLM.ipynb
  docs/_config.yml
  docs/_data/navigation.yml
  docs/_includes/docs-langtest-pagination.html
  docs/_includes/head.html
  docs/_includes/pagination.html
  docs/_includes/scripts/article.js
  docs/_includes/scripts/custom.js
  docs/_layouts/landing.html
  docs/_sass/custom.scss
  docs/pages/benchmarks/asdiv.md
  docs/pages/benchmarks/bbq.md
  docs/pages/benchmarks/benchmark.md
  docs/pages/benchmarks/bigbench.md
  docs/pages/benchmarks/boolq.md
  docs/pages/benchmarks/commonsenseqa.md
  docs/pages/benchmarks/fiqa.md
  docs/pages/benchmarks/hellaswag.md
  docs/pages/benchmarks/legalbench.md
  docs/pages/benchmarks/logiqa.md
  docs/pages/benchmarks/mmlu.md
  docs/pages/benchmarks/multilexsum.md
  docs/pages/benchmarks/narrativeqa.md
  docs/pages/benchmarks/natural-questions.md
  docs/pages/benchmarks/openbookqa.md
  docs/pages/benchmarks/piqa.md
  docs/pages/benchmarks/quac.md
  docs/pages/benchmarks/siqa.md
  docs/pages/benchmarks/truthfulqa.md
  docs/pages/benchmarks/xsum.md
  docs/pages/docs/data.md
  docs/pages/docs/getting_started.md
  docs/pages/docs/hub.md
  docs/pages/docs/installation.md
  docs/pages/docs/langtest_versions/release_notes.md
  docs/pages/docs/langtest_versions/release_notes_1_0_0.md
  docs/pages/docs/langtest_versions/release_notes_1_1_0.md
  docs/pages/docs/langtest_versions/release_notes_1_2_0.md
  docs/pages/docs/langtest_versions/release_notes_1_3_0.md
  docs/pages/docs/langtest_versions/release_notes_1_4_0.md
  docs/pages/docs/langtest_versions/release_notes_1_5_0.md
  docs/pages/docs/langtest_versions/release_notes_1_6_0.md
  docs/pages/docs/model.md
  docs/pages/docs/one_liner.md
  docs/pages/docs/task.md
  docs/pages/tests/ideology.md
  docs/pages/tests/ideology/political_compass.md
  docs/pages/tests/test.md
  docs/pages/tutorials/Benchmark_Dataset_Notebook.md
  docs/pages/tutorials/End_to_End_workflow_Notebooks.md
  docs/pages/tutorials/LLM_Testing_Notebooks.md
  docs/pages/tutorials/Miscellaneous_Notebooks.md
  docs/pages/tutorials/test_specific_notebooks.md
  docs/pages/tutorials/tutorials.md
  langtest/data/config/wino_ai21_config.yml
  pyproject.toml
Labels: 📚 Documentation

#896 Model Selection Option and Save harness.run() Results
  langtest/langtest.py
  langtest/utils/custom_types/sample.py
  tests/test_harness.py
Labels: 💡Enhancements, 🚀 Current Release
